[package]
authors = [
  "Benjamin Coenen <benjamin.coenen@hotmail.com>",
]
edition = "2018"
license = "Apache-2.0"
name = "wasmer-provider"
publish = false
version = "1.0.0-alpha.1"

[features]
default = ["native-tls"]
native-tls = ["kube/native-tls", "kubelet/kube-native-tls", "krator/kube-native-tls"]
rustls-tls = ["kube/rustls-tls", "kubelet/rustls-tls", "krator/rustls-tls"]

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
backtrace = "0.3"
cap-std = "0.13"
chrono = {version = "0.4", features = ["serde"]}
futures = "0.3"
krator = {version = "0.4", default-features = false}
kube = {version = "0.58", default-features = false}
kubelet = {path = "../kubelet", version = "1.0.0-alpha.1", default-features = false, features = ["derive"]}
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tempfile = "3.1"
tokio = {version = "1.0", features = ["fs", "macros", "io-util", "sync"]}
tracing = {version = "0.1", features = ['log']}
wasi-cap-std-sync = "0.28"
wasi-common = "0.28"
wasmtime = "0.28"
wasmtime-wasi = "0.28"
wat = "1.0.38"
wasi-experimental-http-wasmtime = "0.5.0"
# TODO use upstream version when merged
wasmer = { version = "2.0.0", git = "https://github.com/bnjjj/wasmer", branch = "feat_send_sync_resolver" }
wasmer-wasi = { version = "2.0.0", git = "https://github.com/bnjjj/wasmer", branch = "feat_send_sync_resolver" }

[dev-dependencies]
k8s-openapi = {version = "0.12", default-features = false, features = ["v1_21", "api"]}
oci-distribution = {path = "../oci-distribution", version = "0.7"}
