export RUST_LOG := "main=debug"

build +FLAGS='':
    cargo build {{FLAGS}}

build-wasm +FLAGS='':
    cargo build --target wasm32-wasi --release {{FLAGS}}

test:
    cargo fmt --all -- --check
    cargo clippy --workspace
    cargo test --workspace
